{% set name = "openscm-runner" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aa1887d9356c11ed4b6ae8f502440b40d17b82220a79949e170daa39d4fe8f7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm

  run:
    - python >=3.7
    - click
    - openscm-units >=0.5.0
    - pyam >=1.2
    - python-dotenv
    - scmdata >=0.7.4
    - tqdm
    - importlib-metadata

test:
  imports:
    - openscm_runner
  requires:
    - pip
  commands:
    - pip check
    - python -c "import openscm_runner; print(openscm_runner.__version__); assert openscm_runner.__version__ == '{{ version }}'"

about:
  home: https://github.com/openscm/openscm-runner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Thin wrapper to run simple climate models (emissions driven runs only)
  doc_url: https://openscm-runner.readthedocs.io/en/stable/
  dev_url: https://github.com/openscm/openscm-runner

extra:
  recipe-maintainers:
    - znicholls
